name: release-table-webview

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release'
        required: true
        options:
          - table-webview

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.package }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn build
      - name: Publish ${{ inputs.package }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
